Generic driver and screenshots
testproject-io/robot-library pull request #10
Opened 2020-12-13 09:41 UTC by Rantzur1992

Added a keyword to create a step.
Added the possibility of spawning a generic driver session.

2020-12-14 09:45 UTC, vitalybu requested changes

2020-12-14 09:45 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +    def create_step(self, description, message, passed=True, screenshot=True):
Screenshot should not be taken by default:
```python
def create_step(self, description, message, passed=True, screenshot=False):
```

2020-12-14 09:45 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
>          self.library = SeleniumLibrary()
How come library is not prefixed with `__` as well?

2020-12-14 09:45 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +            driver.report().step(message="Set timeout", description=f"Time out was set to {timeout}", passed=True)
```python
driver.report().step(message="Set timeout", description=f"Time out was set to {timeout} milliseconds", passed=True)
```

2020-12-14 09:45 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +        if not isinstance(driver, webdriver.Generic):
Checking the instance of the driver here is a bit strange.
Why not set `self.__is_generic` to true when creating the driver itself and simply check this flag here?

2020-12-14 09:45 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +                description="Create Generic Driver",
The message is redundant.
You can set the message to "Generic Driver" and the description to "New session created", or something like this..

2020-12-14 12:07 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +        if not isinstance(driver, webdriver.Generic):
If it is set to True by default, where do you want to set it to false in case it is not generic?

2020-12-14 12:16 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +    def create_step(self, description, message, passed=True, screenshot=True):
Changed

2020-12-14 12:17 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
>          self.library = SeleniumLibrary()
Changed to __

2020-12-14 12:18 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +            driver.report().step(message="Set timeout", description=f"Time out was set to {timeout}", passed=True)
Changed, thanks.

2020-12-14 12:19 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +                description="Create Generic Driver",
Noted.

2020-12-14 18:59 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +        if not isinstance(driver, webdriver.Generic):
I didn't say to set it to `True` by default. It should remain `False`.
You can set it to `True` on line 139, right after creating the "Generic Driver"

2020-12-14 19:01 UTC, vitalybu commented
Commit 2499ade95fa8640a4fbfaf946df08ba80b91eea3 should've been a fixup commit that will be squashed after the review... No need to mess up the git history.

2020-12-15 06:47 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +        if not isinstance(driver, webdriver.Generic):
Noted, removed the isinstance check.

2020-12-15 08:18 UTC, vitalybu commented on TestProjectLibrary/TestProjectLibrary.py
> +            driver.report().disable_command_reports(True)
Why do we disable the command reports for non generic drivers?
Also, please squash the two commits into a single one.

2020-12-15 08:19 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +            driver.report().disable_command_reports(True)
It is always like that, it disables automatic reports.
We build the reports in the library itself.

2020-12-15 08:32 UTC, Rantzur1992 commented on TestProjectLibrary/TestProjectLibrary.py
> +            driver.report().disable_command_reports(True)
Also squashed the commits.

2020-12-15 08:41 UTC, vitalybu approved these changes

2020-12-15 08:47 UTC, merged